// File generated by FlutterFire CLI.
// ignoring_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwMRul8kOkkK3yyfz1NfSFQb9aJy6XZr0',
    appId: '1:732185606344:android:5b696f79ee265733744dfd',
    messagingSenderId: '732185606344',
    projectId: 'eamau-auth',
    storageBucket: 'eamau-auth.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5eUuCJEF1fH-GZbXUenSMM8a8gMg4rhM',
    appId: '1:732185606344:ios:4297df81da228b34744dfd',
    messagingSenderId: '732185606344',
    projectId: 'eamau-auth',
    storageBucket: 'eamau-auth.firebasestorage.app',
    androidClientId: '732185606344-pe03j44l9vepa1flmj5c7f0qd025cc8t.apps.googleusercontent.com',
    iosClientId: '732185606344-5mp176lffqnpn1pjr78k9pefbvgshfu5.apps.googleusercontent.com',
    iosBundleId: 'org.eamau.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MACOS_MESSAGING_SENDER_ID',
    projectId: 'eamau-auth',
    storageBucket: 'eamau-auth.appspot.com',
    iosBundleId: 'com.example.eamau',
  );

  // Linux configuration: reuse the Android values present in this repo.
  // If you have a dedicated Linux app in Firebase, replace these with the
  // correct Linux app values from the Firebase Console.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBwMRul8kOkkK3yyfz1NfSFQb9aJy6XZr0',
    appId: '1:732185606344:android:5b696f79ee265733744dfd',
    messagingSenderId: '732185606344',
    projectId: 'eamau-auth',
    storageBucket: 'eamau-auth.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_WEB_MESSAGING_SENDER_ID',
    projectId: 'eamau-auth',
    authDomain: 'eamau-auth.firebaseapp.com',
    storageBucket: 'eamau-auth.appspot.com',
  );
}
